export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const PROJECT_ROLES = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
} as const;

export const PROJECT_TYPES = {
  SINGLE: 'SINGLE',
  ORGANIZATION: 'ORGANIZATION',
} as const;

export const CHART_TYPES = {
  BAR: 'BAR',
  LINE: 'LINE',
  PIE: 'PIE',
  SCATTER: 'SCATTER',
  COLUMN_3D: 'COLUMN_3D',
  BAR_3D: 'BAR_3D',
  LINE_3D: 'LINE_3D',
} as const;